### ISSUE TITLE
about the classification?

### ISSUE THREAD

**Issue by xiaomabufei** [tomeramit/SegDiff#5]
hello, have you considered the classification issue?  How do you handle the categories, please?

**Comment by tomeramit** [comment]
can you elaborate? I dont understand your question/meaning

**Comment by xiaomabufei** [comment]
Thank you for your reply!  I mean, do you consider the category of mask in your task settings.  Do you generate masks for one category at a time or for all categories at once ?

**Comment by xiaomabufei** [comment]
![image](https://user-images.githubusercontent.com/104605826/233825774-5aa59f5c-afb4-456f-8f15-b965d382fee0.png)
what the meaning of this phrase? Looking forward to your reply!!

**Comment by xiaomabufei** [comment]
@tomeramit  Can you elaborate on your mission setting?  Thank you very much!!

**Comment by tomeramit** [comment]
The framework is for binary classification while Cityscapes is a semantic segmentation dataset. Therefore, in the paper, we split it into per-object datasets. This means that we created separate datasets for buses, cars, etc., in order to have a binary segmentation dataset. We did this to compare it with the other models in the benchmark that also perform binary segmentation.

**Comment by tomeramit** [comment]
I'm closing the issue, in feel free to reopen in case you want
